package wallet

const (
	RS_FUNDING_BROADCASTED ChannelStatus = CS_FUNDING_BROADCASTED
	RS_FUNDING_CONFIRMED   ChannelStatus = CS_FUNDING_CONFIRMED
	RS_ANCHOR_BROADCASTED  ChannelStatus = CS_ANCHOR_BROADCASTED
	RS_ANCHOR_CONFIRMED    ChannelStatus = CS_ANCHOR_CONFIRMED

	RS_PAYMENT_STARTED     ResvStatus = 0x100
	RS_PAYMENT_BROADCASTED ResvStatus = 0x101
	RS_PAYMENT_CONFIRMED   ResvStatus = 0x102

	RS_SPLICINGIN_STARTED            ResvStatus = 0x200
	RS_SPLICINGIN_BROADCASTED        ResvStatus = 0x201
	RS_SPLICINGIN_CONFIRMED          ResvStatus = 0x202
	RS_SPLICINGIN_ANCHOR_BROADCASTED ResvStatus = 0x203
	RS_SPLICINGIN_ANCHOR_CONFIRMED   ResvStatus = RS_CONFIRMED

	RS_SPLICINGOUT_STARTED            ResvStatus = 0x300
	RS_SPLICINGOUT_ANCHOR_BROADCASTED ResvStatus = 0x301
	RS_SPLICINGOUT_ANCHOR_CONFIRMED   ResvStatus = 0x302
	RS_SPLICINGOUT_BROADCASTED        ResvStatus = 0x303
	RS_SPLICINGOUT_CONFIRMED          ResvStatus = RS_CONFIRMED
)
