export namespace Message {
  export enum Channel {
    INJECT_CONTENT = 'INJECT_CONTENT',
    BG_POPUP = 'BG_POPUP',
  }
  export enum Port {
    INJECT_CONTENT = 'INJECT_CONTENT',
    CONTENT_BG = 'CONTENT_BG',
    BG_POPUP = 'BG_POPUP',
  }
  export enum MessageType {
    REQUEST = 'REQUEST',
    APPROVE = 'APPROVE',
    EVENT = 'EVENT',
  }
  export enum MessageFrom {
    INJECTED = 'INJECTED',
    CONTENT = 'CONTENT',
    BACKGROUND = 'BACKGROUND',
    POPUP = 'POPUP',
  }
  export enum MessageTo {
    INJECTED = 'INJECTED',
    CONTENT = 'CONTENT',
    BACKGROUND = 'BACKGROUND',
    POPUP = 'POPUP',
  }
  export enum MessageAction {
    GET_APPROVE_DATA = 'GET_APPROVE_DATA',
    GET_APPROVE_DATA_RESPONSE = 'GET_APPROVE_DATA_RESPONSE',
    APPROVE_RESPONSE = 'APPROVE_RESPONSE',
    REJECT_RESPONSE = 'REJECT_RESPONSE',
    REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS',
    GET_ACCOUNTS = 'GET_ACCOUNTS',
    GET_NETWORK = 'GET_NETWORK',
    SWITCH_NETWORK = 'SWITCH_NETWORK',
    GET_PUBLIC_KEY = 'GET_PUBLIC_KEY',
    BUILD_BATCH_SELL_ORDER = 'BUILD_BATCH_SELL_ORDER',
    SPLIT_BATCH_SIGNED_PSBT = 'SPLIT_BATCH_SIGNED_PSBT',
    GET_BALANCE = 'GET_BALANCE',
    SEND_BITCOIN = 'SEND_BITCOIN',
    SIGN_MESSAGE = 'SIGN_MESSAGE',
    SIGN_PSBT = 'SIGN_PSBT',
    SIGN_PSBTS = 'SIGN_PSBTS',
    PUSH_TX = 'PUSH_TX',
    PUSH_PSBT = 'PUSH_PSBT',
    GET_INSCRIPTIONS = 'GET_INSCRIPTIONS',
    SEND_INSCRIPTION = 'SEND_INSCRIPTION'
  }
}
